_wandb:
    value:
        cli_version: 0.25.1
        e:
            jcw129uq9vowvj3msnokt34xomvhi921:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                codePath: wandb_test/first_wandb_run.py
                codePathLocal: wandb_test/first_wandb_run.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "240252551168"
                email: maxpendse@gmail.com
                executable: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
                git:
                    commit: 8c6db5459c6e13fc63af1eb226e9e1b4bc1e8f7e
                    remote: https://github.com/Max178/Max-Post-Training-Tests.git
                host: Maxs-MacBook-Air-3.local
                memory:
                    total: "8589934592"
                os: macOS-13.5-arm64-arm-64bit
                program: /Users/maxpendse/Desktop/Coding Projects/Max-Post-Training-Tests/wandb_test/first_wandb_run.py
                python: CPython 3.12.1
                root: /Users/maxpendse/Desktop/Coding Projects/Max-Post-Training-Tests
                startedAt: "2026-04-19T06:08:42.831309Z"
                writerId: jcw129uq9vowvj3msnokt34xomvhi921
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.1
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
dataset:
    value: Breast Cancer SKLearn
epochs:
    value: 25
learning_rate:
    value: 0.002
