_wandb:
    value:
        cli_version: 0.25.1
        e:
            hhbe0vd6bspv6woiaf8978ambgs7vruu:
                codePath: wandb_test/first_wandb_run.py
                codePathLocal: wandb_test/first_wandb_run.py
                email: maxpendse@gmail.com
                executable: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
                git:
                    commit: 8c6db5459c6e13fc63af1eb226e9e1b4bc1e8f7e
                    remote: https://github.com/Max178/Max-Post-Training-Tests.git
                host: Maxs-MacBook-Air-3.local
                os: macOS-13.5-arm64-arm-64bit
                program: /Users/maxpendse/Desktop/Coding Projects/Max-Post-Training-Tests/wandb_test/first_wandb_run.py
                python: CPython 3.12.1
                root: /Users/maxpendse/Desktop/Coding Projects/Max-Post-Training-Tests
                startedAt: "2026-04-19T06:27:36.346924Z"
                writerId: hhbe0vd6bspv6woiaf8978ambgs7vruu
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.1
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
dataset:
    value: Breast Cancer SKLearn
epochs:
    value: 25
learning_rate:
    value: 0.01
